import { Form, FormResponse } from '@/types/form'
import { useConvexAuth, useMutation, useQuery } from 'convex/react'
import { api } from '@/convex/_generated/api'
import { Id } from '@/convex/_generated/dataModel'

// Hook-based storage using Convex. The signed-in user is identified on the
// server from their Clerk token, so no user id is ever sent from here.
export function useStorage() {
  const { isAuthenticated } = useConvexAuth()

  const saveFormMutation = useMutation(api.forms.saveForm)
  const getAllFormsQuery = useQuery(
    api.forms.getAllForms,
    isAuthenticated ? {} : "skip"
  )
  const deleteFormMutation = useMutation(api.forms.deleteForm)
  const saveResponseMutation = useMutation(api.responses.saveResponse)
  const generateUploadUrl = useMutation(api.files.generateUploadUrl)

  return {
    // Forms
    saveForm: async (form: Form) => {
      if (!isAuthenticated) throw new Error('User not authenticated')
      
      // First, try to find existing form by title to get Convex ID
      const allForms = getAllFormsQuery || []
      const existing = allForms.find(f => f.title === form.title)
      
      if (existing) {
        // Update existing form
        const existingId = existing._id
        await saveFormMutation({
          id: existingId,
          title: form.title,
          description: form.description,
          isQuiz: form.isQuiz,
          timerMinutes: form.timerMinutes,
          fields: form.fields,
          createdAt: form.createdAt,
          updatedAt: form.updatedAt,
        })
        return existingId
      } else {
        // Create new form
        const formId = await saveFormMutation({
          id: '', // Will be generated by Convex
          title: form.title,
          description: form.description,
          isQuiz: form.isQuiz,
          timerMinutes: form.timerMinutes,
          fields: form.fields,
          createdAt: form.createdAt,
          updatedAt: form.updatedAt,
        })
        return formId
      }
    },

    getForm: (id: string): Form | undefined => {
      // First try from user's forms (if signed in)
      if (isAuthenticated) {
        const forms = getAllFormsQuery || []
        const found = forms.find(f => {
          const formId = f._id
          return String(formId) === String(id)
        })
        if (found) {
          const formId = found._id
          return {
            id: formId,
            title: found.title,
            description: found.description,
            isQuiz: found.isQuiz,
            timerMinutes: found.timerMinutes,
            fields: found.fields,
            createdAt: found.createdAt,
            updatedAt: found.updatedAt,
          }
        }
      }
      // For public viewing, we need to use a different approach
      // Since we can't use useQuery conditionally, we'll need to handle this in the component
      // For now, return undefined and let the component handle it
      return undefined
    },

    getAllForms: (): Form[] => {
      const forms = getAllFormsQuery || []
      return forms.map(f => {
        const formId = f._id
        return {
          id: formId,
          title: f.title,
          description: f.description,
          isQuiz: f.isQuiz,
          timerMinutes: f.timerMinutes,
          fields: f.fields,
          createdAt: f.createdAt,
          updatedAt: f.updatedAt,
        }
      })
    },

    deleteForm: async (id: string) => {
      if (!isAuthenticated) throw new Error('User not authenticated')
      await deleteFormMutation({ id: id as Id<"forms"> })
    },

    // Responses
    saveResponse: async (response: FormResponse) => {
      // The formId should already be a Convex ID string
      // Try to use it directly, or find from user's forms as fallback
      let convexFormId: Id<"forms">
      
      // Try to use formId directly (it should be a Convex ID)
      if (response.formId && typeof response.formId === 'string') {
        convexFormId = response.formId as Id<"forms">
      } else {
        // Fallback: find from user's forms
        const allForms = getAllFormsQuery || []
        const form = allForms.find(f => {
          const fId = f._id
          return String(fId) === String(response.formId)
        })
        
        if (!form) {
          console.error('Form not found for response:', response.formId)
          return
        }
        convexFormId = form._id
      }

      await saveResponseMutation({
        formId: convexFormId,
        responses: response.responses,
        submittedAt: response.submittedAt,
        studentName: response.studentName,
        studentClass: response.studentClass,
        tabSwitchCount: response.tabSwitchCount,
        pasteAttempts: response.pasteAttempts,
        attachments: response.attachments,
      })
    },

    // Uploads a file to Convex storage and returns its storage id
    uploadFile: async (file: File): Promise<string> => {
      const uploadUrl = await generateUploadUrl()
      const result = await fetch(uploadUrl, {
        method: 'POST',
        headers: { 'Content-Type': file.type },
        body: file,
      })
      if (!result.ok) {
        throw new Error('Failed to upload file')
      }
      const { storageId } = await result.json()
      return storageId as string
    },
  }
}
